name: Toolforge

on:
  - push
  - workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: garygrossgarten/github-action-ssh@2b10f41b5a33808f6d24eafd253296766308b7c4
        with:
          command: >-
            become sdzerobot bash -c '
              cd /data/project/sdzerobot/mwn || exit 1;
              if [[ "$(git pull | grep -c "Already up to date")" -eq 0 ]]; then
                if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c package.json)" -gt 0 ]]; then
                  echo "Running npm install for mwn ...";
                  npm install || exit 1;
                fi;
                echo "Building mwn ...";
                npm run quickbuild;
              fi;
              cd /data/project/sdzerobot/SDZeroBot || exit 1;
              echo "Pulling SDZeroBot ...";
              git pull || exit 1;
              if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c package.json)" -gt 0 ]]; then
                echo "Running npm install for SDZeroBot ...";
                npm install || exit 1;
              fi;
              echo "Building SDZeroBot ...";
              npm run tsc;
              if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c crontab)" -gt 0 ]]; then
                echo "Updating the crontab ...";
                crontab crontab;
              fi;
              # Covers everything in eventstream-router/ and external files with "eventstream" in name
              if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c eventstream)" -gt 0 ]]; then
                echo "Restarting eventstream-router ...";
                cd eventstream-router && npm run validate && npm restart;
              fi;
              if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c "webservice/")" -gt 0 ]]; then
                if [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c "webservice/package.json")" -gt 0 ]]; then
                  echo "Running npm install for SDZeroBot/webservice ...";
                  cd /data/project/sdzerobot/SDZeroBot/webservice && npm install --only=production;
                fi;
                echo "Syncing SDZeroBot/webservice with www/js ...";
                cd /data/project/sdzerobot && rsync -avu --delete "SDZeroBot/webservice/" "www/js";
                echo "Restarting SDZeroBot webservice ...";
                cd /data/project/sdzerobot/www/js && npm restart;
              elif [[ "$(git diff --name-only HEAD HEAD@{1} | grep -c "web-endpoint")" -gt 0 ]]; then
                echo "Restarting SDZeroBot webservice ...";
                cd /data/project/sdzerobot/www/js && npm restart;
              fi;
            '
          host: login.toolforge.org
          username: sd
          privateKey: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}

