name: Toolforge

on:
  - push
  - workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: garygrossgarten/github-action-ssh@2b10f41b5a33808f6d24eafd253296766308b7c4
        with:
          command: >-
            become sdzerobot bash -c '
              cd /data/project/sdzerobot/mwn || exit 1;
              if [[ "$(git pull | grep "Already up to date" | wc -l)" -eq 0 ]]; then
                if [[ "$(git diff --name-only HEAD HEAD~1 | grep package.json | wc -l)" -gt 0 ]]; then
                  npm install || exit 1;
                fi;
                npm run quickbuild;
              fi;
              cd /data/project/sdzerobot/SDZeroBot || exit 1;
              git pull || exit 1;
              if [[ "$(git diff --name-only HEAD HEAD~1 | grep package.json | wc -l)" -gt 0 ]]; then
                npm install || exit 1;
              fi;
              npm run build || exit 1;
              if [[ "$(git diff --name-only HEAD HEAD~1 | grep crontab | wc -l)" -gt 0 ]]; then
                crontab crontab;
              fi;
              if [[ "$(git diff --name-only HEAD HEAD~1 | grep eventstream-router | wc -l)" -gt 0 ]]; then
                cd eventstream-router && npm restart;
              fi;
            '
          host: login.toolforge.org
          username: sd
          privateKey: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}

